version: "3"
services:
    mongodb:
        image: 'mongo'
        #image: '/location/mongo' : có thể đặt hình ảnh là nơi lưu trữ hoặc là link của image ?
        volumes:
            - data:/data/db:ro
        #environments: Di chuyển các biến môi trường bằng cách tạo file mongo.env
            #- MONGO_INITDB_ROOT_USERNAME=root
            #- MONGO_INITDB_ROOT_PASSWORD=password
            #- MONGO_INITDB_DATABASE=mydb 
        env_file:
            - ./env/mongo.env
        networks:
            - goals-net
#Định nghĩa volumes toàn cục, có nghĩa là volumes sẽ sử dụng cho các container, không gắn vào bất kì dịch vụ cụ thể nào 
volumes:
    data: 
    backend:
    frontend:
